spring.application.name=pfebackend

# Configuration MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/users_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Port du serveur
server.port=8080

# Taille maximale d'un fichier
spring.servlet.multipart.max-file-size=50MB
# Taille maximale totale d'une requête (plusieurs fichiers)
spring.servlet.multipart.max-request-size=50MB